### ISSUE TITLE
Consider having `showMessage` et al be associated with a request id

### ISSUE THREAD

**Issue by jvican** [scalacenter/bsp#3]
LSP has a `showMessage` notification, as well as others that serve a similar purpose, to notify the clients (editors) about what's happening in the server.
  
BSP builds upon this infrastructure, but there is a key difference between BSP and LSP in terms of requirements: BSP needs to handle parallel requests, while LSP doesn't.
  
This means that when clients (in our case, IDEs, editors and users) want to run tests of different modules in parallel (or similar tasks that require parallel execution) there is no way to know which request trigger certain logs.
  
We need to figure out what to do to allow clients to separate logs coming from different requests. Should we add another `showMessage` notification that is associated with a request id?
  
This question came up when thinking about the Intellij integration with @jastice.

**Comment by jastice** [comment]
More generally, any request can have a whole tree/graph of things it is doing in parallel. 

In the case of tests:
test task -> test suites -> individual tests -> test logs/exceptions, running status (started/ended), result

or builds:
build task -> subprojects/build targets -> individual files -> status of file (compiler phase), error messages, warnings, etc

For many of these things we already have the ability to show a detailed status in the UI, and in some cases do, depending on the individual tool integration. When delegating tasks to sbt it is rather hard to do because of the concurrency in many tasks and unstructured log output (server integration can change this).

The full level of detail may not be necessary for many things, but tree-structured notifications would make it easier to update UI elements in realtime individually. This is also the case for CI tools.

**Comment by olafurpg** [comment]
>  BSP needs to handle parallel requests, while LSP doesn't.

Nitpick, LSP supports parallel requests and `$/cancelRequest` would not exist if servers could not process requests in parallel. `window/showMessage` on the other hand does not take this into account. 

> Should we add another showMessage notification that is associated with a request id?

I think it's possible to extend ShowMessageParams to include an `requestId: number` https://microsoft.github.io/language-server-protocol/specification#showmessage-notification-arrow_left
```ts
interface ShowMessageParamsWithId extends ShowMessageParams {
  /* The request id associated with this notification */
  requestId: number?
}
```

Existing clients would be expected to ignore this field, and new clients could use it if they choose.

> In the case of tests:
> or builds:

I think it makes sense to introduce custom notification types to report progress on test execution and compilation. `window/showMessage` is intended for console-style log output.

**Comment by olafurpg** [comment]
To clarify, I think it's a better idea to introduce custom notification messages to report test/build progress instead of extending showMessage.

Related, there is a related LSP ticket on "Add support to report progress for a running request" https://github.com/Microsoft/language-server-protocol/issues/70 I think it would make sense to draw inspiration from there.

**Comment by jastice** [comment]
builds and tests may merit special support, but in the case of generic tasks with unspecified semantics, the same considerations can apply.

For instance I could create a `deploy` task for my project that uploads binaries to several target servers in parallel, and I would like to get a updates on which of these have started, completed successfully, with error, etc. 

This is a bit academic since I don't think most build tools support this kind of structured logging in their APIs, but this lack has been one of my favorite pain points for a long time.

**Comment by SethTisue** [comment]
Discourse thread: https://contributors.scala-lang.org/t/adding-try-with-resource-to-scala/1641

**Comment by jvican** [comment]
> Nitpick, LSP supports parallel requests and $/cancelRequest would not exist if servers could not process requests in parallel. window/showMessage on the other hand does not take this into account.
  
You're right, the main issue here is that LSP clients just output all logs to a buffer, and all messages to the end users, so there is no such a pressing need to map things back to the request that originated it.
  
With regard to making notification messages report only test/build progress, I think we should aim for a more general mechanism that allows us to support other tasks, as Justin mentions.
  
> I think it's possible to extend ShowMessageParams to include an requestId: number microsoft.github.io/language-server-protocol/specification#showmessage-notification-arrow_left
  
This is exactly what I had in mind, but not only for show message but for log message and similar notifications too.

**Comment by olafurpg** [comment]
> just output all logs to a buffer,

That's the semantics of `window/logMessage`, which is useful for many applications. But complex task graphs could benefit from more structure.

> I think we should aim for a more general mechanism that allows us to support other tasks, as Justin mentions.

I agree. This mechanism could support 

* notifying progress with start/tick/end (to render progress bars)
* report failure
* action buttons such as restart/stop/... (string ID + json args to be passed to `workspace/executeCommand`, similar to how `textDocument/codeAction` and `codeLens` work )

@jastice any suggestion for how this could look like on the protocol layer?

**Comment by jastice** [comment]
I haven't really worked much with bsp/lsp so I don't have concrete suggestions. Just these notes:

* if concurrent independent requests are supported by the protocol and server, requests might need an unique id given by the client that can be referenced from notifications.
* if you have concurrent tasks running on the server only for a single request, and no out-of-band notifications, you may still want to group individual notifications by giving them an id
* giving notifications an `id` and optional `parentId` field allows modeling a tree-structure if desired
* requiring clients to generate a unique request id allows using the same `parentId` field 
* allowing a list of `parentId` allows modeling DAGs, but that's probably over-engineered

Possible model:
* events that form a sequence and change the state of a task (like start/tick/end) have the same `id`
* events that are a subtask (test in test suite, file in compilation) of another and possibly parallelized reference it in `parentId`
* `parentId` can be a request id from the client, or any other event id

**Comment by eed3si9n** [comment]
There are several properties that might be interesting to think about:
- terminal sessions
- origin request ID
- subproject name (aka build target)
- subproject relationship for classpath (`dependsOn(...)` in sbt)
- subproject relationship for command propagation (`aggregate(...)` in sbt)

### terminal sessions

For language servers, probably the first place to start would be the terminal sessions. Example would be client/editor A and client/editor B both connect to server X. One of the options to consider is subscribing to just the events for your terminal session, or scanning all events targeting all sessions.

If you have that, that could split the log output for subproject A and B without changing the LSP data structure. It would automatically work for all LSP clients. This of course means that request of the command is handled one at a time. The type of concurrent _command_ processing would be limited, so I don't think that's too bad.

sbt 1 implements `run` in terms of `bgRun` so eventually `run` wouldn't block other clients from running another command (https://github.com/sbt/sbt/issues/2804). Running `test` would be similar deal.

### originating request ID

Tagging the events with originating request ID might be useful in some cases. But I am not sure if it's always possible at the level of logger to always know who originated your running task.

Another thing is that if you run `sbt compile` and it starts generating logs from 20 subprojects, they'll all have the same request ID, so while it could be useful in some other context log might not be a good use case for this.

### name (subproject, test suite?)

I am not sure if it's feasible, but let's say we can. If events were tagged with subproject (or test suite) name that might be useful. This might be used to split each subproject logs to different tabs if the editor is capable of doing so. These are level of granularity the users are used to thinking.
