### ISSUE TITLE
Add BuildTarget.baseDirectory: Uri

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bsp#50]
Following up from discussions in #30 

Currently, there is no way to associate a `BuildTarget` with a single directory. This information is needed by some IDEs like IntelliJ in order to group together related targets such as `main` and `test`.

Based on discussions in #30, we should add a new field to the `BuildTarget` data structure
```diff
trait BuildTarget {
+ /** The directory where this target belongs to. Multiple build targets are allowed to map
+  * to the same base directory. A base directory does not determine the sources 
+  * of a target, see buildTarget/sources.
+ def baseDirectory: Uri
}
```

At the moment, the IntelliJ Scala plugin infers the base directory from `BuildTargetIdentifier.uri` path ignoring the URI fragment/query-parameters. Build target URIs are supposed to be opaque IDs, which the build tool is free to encode in any way it likes.

**Comment by olafurpg** [comment]
@wisechengyi

> Is BuildTarget.baseDirectory supposed to be source root? If that's the case, I can imagine it being useful since Pants does export this info to IntelliJ in order to configure module's source root correctly.

Is a pants "source root" shared for multiple pants targets? My understanding of the IntelliJ module system is that different modules cannot share an intellij "source root".

There is a `buildTarget/sources` request that determines the source files and directories of a build target https://github.com/scalacenter/bsp/pull/47 which should translate to intellij "source root".

**Comment by jvican** [comment]
> Currently, there is no way to associate a BuildTarget with a single directory.
  
Maybe I'm misunderstanding but `BuildTargetIdentifier` allows clients to know what single directory is associated with a build target:
  
>A unique identifier for a target, usually the project base directory.
>
>```scala
>trait BuildTargetIdentifer {
>  /** The target’s Uri */
>  def uri: Uri
>}
>```

However, as mentioned in #30, there are some targets that share the same project directory (targets cross-compiling with different compiler versions is the best example). Right now, to disambiguate these projects the build server is responsible for adding a query parameter such that the resulting URIs are different.
  
(Note that the URI represents the project base directory, not the root base directory. For example, the root directory can be `/code/my-buiild` and the project base directories can be `/code/my-build/a` -- the project base directory can even be defined in another directory that is not a parent of the root directory.)
  
The previous encoding has been sufficient so far and it's at the freedom of the build server to keep that invariant so that projects don't clash. IntelliJ then shows a list of all the targets under the BSP project list adequately.
  
The problem we've had so far is that this encoding doesn't make `name` explicit and then, IntelliJ, has added support for parsing the name from the query parameter of the URI when the build server presents the client with a URI such as `file:///code/my-build/a?name=a`.
  
The problem at hand seems to beg for a solution. I then suggest we should add a field `def name: String` to `BuildTarget` and continue representing the base directory in the project's URI. I also propose that we continue to ask the build server to keep the URI unique.

**Comment by jvican** [comment]
> A unique identifier for a target, usually the project base directory.
  
Another required change would be to write in the protocol that the `def uri: Uri` in the build target identifier must be the project base directory.
  
Note that this approach is consistent with the current protocol and the other data structures that we use, that they all have a `def uri: Uri` such as `TextDocumentIdentifier`, `SourceItem`, `ResourceItem`, etc.

**Comment by olafurpg** [comment]
> BuildTargetIdentifier allows clients to know what single directory is associated with a build target:

I propose we reformulate the spec on `BuildTargetIdentifier` to clarify the URI

```diff
- A unique identifier for a target, usually the project base directory.
+ A unique identifier for a target, can use any URI-compatible encoding 
+ as long as it is unique within the workspace.
+ Clients should not infer metadata out of the URI structure such as
+ the path or query parameters, use `BuildTarget` instead.
```

---

> we should add a field `def name: String` to `BuildTarget`

There already exists a field `BuildTarget.displayName` for this purpose. The `BuildTargetIdentifier` is only to uniquely identify a build target, the `BuildTarget` structure is responsible for communicating metadata.

**Comment by jvican** [comment]
If `displayName: String` already exists even better, my proposal could be summarized as "let's write in the protocol that the path of the `BuildTargetIdentifier` can be used to know the project base directory".
  
I do not believe we need `baseDirectory: Uri` in `BuildTarget` when we already use a URI in the ID, whose path *is* the project base directory. The ID is used in the same way for data structures like `TextDocument`, we don't add a new `path: Uri` field.

**Comment by olafurpg** [comment]
From https://github.com/scalacenter/bsp/issues/30#issuecomment-433323536

> For example in my prototype bsp implementation for mill, the BuildTargetIdentifier was just the string you pass to the mill command-line to run this target, that was really convenient.

In build tools like pants/bazel, the target URI is commonly relative `//a/b:c` and cannot be mapped to a directory without the workspace root.

**Comment by jvican** [comment]
> In build tools like pants/bazel, the target URI is commonly relative //a/b:c and cannot be mapped to a directory without the workspace root.
  
But the BSP server runs at the workspace and knows all the defined targets, it surely knows the base directory per target and can add it to the URI.
  
Also, `//a/b:c` in bazel/pants or a simple string in mill can be encoded in both the `displayName: String` and can be part of the query parameter of the `URI` in `BuildTargetIdentifier`.

**Comment by olafurpg** [comment]
As a design principle I think we should encode metadata in JSON objects and avoid embedding information in the build target URI, which is supposed to be only a "unique resource **identifier**"

>  A unique identifier for a target, can use any URI-compatible encoding as long as it is unique within the workspace.

**Comment by jvican** [comment]
I understand that's what you're getting at, but that's inconsistent with `TextDocumentIdentifier` in BSP where the ID is not only an identifier but also a path to a file that can be used. That's why I think it's fine to keep the same standard for `BuildTargetIdentifier` too. It also simplifies the API significantly.

**Comment by olafurpg** [comment]
Unlike `TextDocumentIdentifier`, a `BuildTargetIdentifier` does not point to a resource that can be read from disk. The only critical attribute of a build target URI is that it is unique.

I think it's important that build server authors can choose the most natural and readable encoding to uniquely represent build target in a workspace. For example, Bloop could use `core` instead of `file:///path/to/workspace/?id=core`.

**Comment by jvican** [comment]
> Unlike TextDocumentIdentifier, a BuildTargetIdentifier does not point to a resource that can be read from disk. The only critical attribute of a build target URI is that it is unique.
  
I know it does not point to a resource that can be read, that's exactly my point. They have both `Identifier` in the name and they have arbitrarily different semantics. 
  
> I think it's important that build server authors can choose the most natural and readable encoding to uniquely represent build target in a workspace.
  
What's the use case for that? IDEs will want to show the display name, not the URI.

**Comment by jastice** [comment]
Agree with @olafurpg - for debugging purposes, we should allow the `BuildTargetIdentifier` to be as close as possible to the build tool's internal target id.

For somebody writing a client, having an explicit field for base directory is also more intuitive and straightforward than making assumptions about the shape of the identifier.

**Comment by jvican** [comment]
Fine, but I'm not comfortable with the current inconsistency in the protocol. If you want to add `baseDirectory: Uri` to `BuildTarget`, I propose you change `TextDocumentIdentifier` to `TextDocument` and only leave the suffix `Identifier` for something that is required to be unique, but that requires no assumptions on the client side. Otherwise, we should keep it as is.

**Comment by olafurpg** [comment]
> Otherwise, we should keep it as is.

Are you against opposed to adding `BuildTarget.baseDirectory` unless `TextDocumentIdentifier` is renamed to `TextDocument`? I don't think that is necessary, both `BuildTargetIdentifier` and `TextDocumentIdentifier` are both resource identifiers but they are loaded/read in different ways  

- build target resources are read via the BSP protocol
- text document resources are read from OS file system

If we rename to `TextDocument` then I would expect the data structure to include the full text contents and other metadata such as [SemanticDB `TextDocument`](https://scalameta.org/docs/semanticdb/specification.html#textdocument). The current `TextDocumentIdentifier` is identical to LSP `TextDocumentIdentifier`.

**Comment by jvican** [comment]
> but they are loaded/read in different ways
  
I'm proposing to make that explicit in the name.
  
If I've understood you correctly in this thread, your argument to add `baseDirectory` to `BuildTarget` is that clients should not make any assumption about identifiers and not rely on their paths.
  
However, we've made it already clear that there's a discrepancy between `BuildTargetIdentifier` and `TextDocumentIdentifier` in this regard, as the last one has the extra assumption of asking the client to use the path of the URI to access the document.
  
My claim is that this is confusing. If I follow this maxim, I would also expect myself to be able to use `path` in the `URI` of `BuildTargetIdentifier`. By not making this requirement explicit in the protocol, a build tool like bazel can pass its own non-existing URI and then break my logic on the client side, especially if I'm checking that the base directory exists or I need to check when its last modified time was.
  
> If we rename to TextDocument then I would expect the data structure to include the full text contents and other metadata such as SemanticDB TextDocument
  
I think we can have `TextDocument` without those fields. If in the future the full text contents are necessary, we can add them. I'm not sure we should have the semanticdb text document in it, though.
  
> The current TextDocumentIdentifier is identical to LSP TextDocumentIdentifier.
  
LSP's use of the suffix "Identifier" is consistent in both `TextDocumentIdentifier` and `VersionedTextDocumentIdentifier`, because both are resources. This consistency does not exist in our protocol.
  
My preferred approach to this problem is to force build tools to encode the `baseDirectory` in the URI of `BuildTargetIdentifier`. Then we can have all identifiers to be accessible via file system.

**Comment by olafurpg** [comment]
Text document contents are not only read from disk, they're also communicated via LSP `textDocument/didChange` notifications and servers are responsible for reproducing the editor buffer state for each text document URI. `TextDocumentIdentifier` is foremost used as an ID and it's not required by the protocol that the scheme is `file://`. 

> My preferred approach to this problem is to force build tools to encode the baseDirectory in the URI of BuildTargetIdentifier

I am not in favor of this solution because I think build target URIs should use the most natural encoding to each build tool. I'm not sure how I can convince any further so I'll leave this to you to decide.

**Comment by jvican** [comment]
> TextDocumentIdentifier is foremost used as an ID and it's not required by the protocol that the scheme is file://.
  
If a client cannot assume that it's `file://`, then it means that it cannot be a resource, since a client cannot read it. I've been completely mislead by your arguments, I thought you were making the argument that it's both a URI and a resource that can be accessed.
  
As it looks like this is not the case, then the protocol is consistent!

**Comment by olafurpg** [comment]
I'm fine keeping things unchanged, but the spec on `BuildTargetIdentifier` should be update in that case so that IntelliJ can rely on the target URI to contain a valid path. 

@jastice @jvican feel free to decide what is best.

**Comment by jastice** [comment]
I somewhat prefer not putting any hard requirements on `BuildTargetIdentifier` that clients would have to make assumptions about. A build target need not have a base directory at all, or may have multiple roots, as in the IntelliJ project model.

**Comment by jvican** [comment]
I'm fine with moving forward with the current proposal. Let's try to get the BSP v2.0 release out soon :smiley_cat:
