### ISSUE TITLE
Support global BSP discovery

### ISSUE THREAD

**Issue by jastice** [scalacenter/bsp#55]
Followup to #32 and #53 

---

#53 defines a method for bsp servers to specify how clients can connect to them without writing tool-specific support. From a usability perspective, it is not optimal because it requires the user to run a command with the tool of choice to generate the connection details.

This can be worked around by adding tool-specific support in the client, but this somewhat goes against the idea of the proposal.

It would be ideal if a client is able to discover installed bsp servers in a standard way, and connect to them without additional user action.

Please discuss proposals

**Comment by jastice** [comment]
Proposal:

There is a global bsp config directory, similar to [Jupyter kernelspecs](https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs) that contains json objects with connection details, just like to project-local definitions in #53. 

Variant 1: by convention, running the connection command in a specific workspace will start the bsp server for that workspace

Variant 2: the workspace is passed as a command line parameter.

Variant 3: the global connection spec doesn't define connection details, only a command to run on a workspace to generate the connection details. If the tool cannnot handle the workspace, it does not generate a connection file and exits with an error. This command should be quick to run, so that all installed tools can be quickly tested for applicability to the workspace.

I think Variant 3 is simple and can piggy-back on the already available discovery mechanism.

In any case, implementing this mechanism is optional for both client and server. It is strictly a usability enhancement.

**Comment by jvican** [comment]
From the discussion in #53, I assume that you and @olafurpg want a standard global directory with the JSON connection file described in the PR as a complement to the current project-level standard `<workspace>/.bsp`. As I read them, these are your arguments:
  
1. You want to minimize the number of times a BSP client fails to find a server. This can happen in freshly cloned repositories where the build tool has not yet run.
2. You don't want to have a connection file per project level because you think that build tools will almost always have the same way of starting a BSP server.
  
I agree these are issues. The most straightforward way of fixing these issues is that I extend #53 to introduce a standard global directory `$XDG_DATA_DIR/.bsp` where we follow the same lookup strategy as the project-level lookup. If a connection file is not found in the workspace, the global directory will be looked up.
  
If this is the case, we will need the following invariants:
  
1. JSON connection files need to be specific to a build tool (name) and a version to allow different versions to have different ways of starting BSP servers.
2. The project-level `.bsp` has precedence over the global `.bsp` standard directory.
  
If we agree on these invariants, I'll incorporate these changes in #53.
  
It seems that some part of your discussion @jastice entails template variables and how you connect to servers (protocol details). I'm opening a new ticket to discuss that -- I have some ideas about how we can have a good story here without supporting the complex solution of kernel specs connection files.

**Comment by jastice** [comment]
> The most straightforward way of fixing these issues is that I extend #53 to introduce a standard global directory $XDG_DATA_DIR/.bsp where we follow the same lookup strategy as the project-level lookup. If a connection file is not found in the workspace, the global directory will be looked up.

Yup, something like this was what I had in mind!

>  JSON connection files need to be specific to a build tool (name) and a version to allow different versions to have different ways of starting BSP servers.

Agree if I understand it right that the files don't have to have a specific name, just needs to be unique.

> The project-level .bsp has precedence over the global .bsp standard directory.

Agree

**Comment by jvican** [comment]
Instead of opening a new ticket, I've made a breakthrough in #52 and pushed a commit to:
  
1. Support the global BSP location
2. Simplify server connections to BSP clients.
  
The new proposal does not need template variables or any kind of communication between the BSP client and the command firing up BSP. Please, feel free to comment on the PR!

**Comment by jvican** [comment]
Fixed via https://github.com/scalacenter/bsp/commit/7ee2a288aafcf738c6efed0bdc88ad7054afd0c1
