### ISSUE TITLE
Scala Native Support

### ISSUE THREAD

**Issue by sorenbug** [scalacenter/bsp#85]
It would be nice to see Scala Native support to be able to build some sort of frontend or IDE around BSP without as much JVM overhead.

Blocked by https://github.com/circe/circe/issues/1077?

**Comment by olafurpg** [comment]
Thanks for reporting! Do you have a particular application in mind? The bsp4s module also depends on Monix 2.3, which I believe is also not published for Scala Native. The lsp4s module (which bsp4s depends on) is not actively maintained, you might want to consider implementing a custom JSON-RPC client library that compiles with Scala Native. In Metals and IntelliJ we use bsp4j.

**Comment by sorenbug** [comment]
I've been thinking for a while about building an IDE in Scala Native (to be less resource intensive) around scalaui, fury/bloop, and metals.

lsp4s = Language Server Protocol for Scala?

**Comment by olafurpg** [comment]
lsp4s is this project here https://github.com/scalameta/lsp4s it has a jsonrpc module that is used by bsp4s

I don't expect we will publish an officially supported Scala Native module for BSP, but I invite you to try and implement one yourself either by forking the jsonrpc module in lsp4s or building from scratch.

From my experience with developing Metals, I am optimistic it's possible to build a low-overhead language server for Scala. I have written a bit about it here

- https://scalameta.org/metals/blog/2019/01/22/bloom-filters.html
- https://scalameta.org/metals/blog/2018/12/12/fast-goto-definition.html

Currently, Metals uses on average well below 100mb of memory even in repos like akka/akka with ~600k lines of Java/Scala code (we index both languages). Being on the JVM gives us access to Java libraries like https://github.com/paul-hammant/qdox, which we use to for example extract Java parameter names in JDK APIs

![screenshot 2019-02-20 at 10 45 17](https://user-images.githubusercontent.com/1408093/53082188-a370ea80-34fc-11e9-9c31-819214155d0d.png)

By default, we'd see `x$1` and `x$2` instead of `beginIndex` and `endIndex`.

I'm happy to chat more in Gitter, but I am afraid there is not much we can do in this repo to fix this issue.
